### ISSUE TITLE
1.4节关于TL与已有概念的区别和联系

### ISSUE THREAD

**Issue by chamwen** [jindongwang/transferlearning-tutorial#13]
################################################################
7. 迁移学习VS 协方差漂移
协⽅差漂移也是迁移学习要研究的问题之⼀，它特指**数据的条件概率分布发⽣变化**。
################################################################

这里表示怀疑，应该是边际分布概率发生变化。
条件概率指的是源域和目标域在同一个样本取值情况下，标签一致，是covariate shift的假设前提
参考：http://sifaka.cs.uiuc.edu/jiang4/domain_adaptation/survey/node8.html

**Comment by jindongwang** [comment]
这个在最新版已修正
