### ISSUE TITLE
有个链接失效了

### ISSUE THREAD

**Issue by eccstartup** [jindongwang/transferlearning-tutorial#18]
`https://github.com/jindongwang/transferlearning/blob/master/doc/dataset.md`
变成了
`https://github.com/jindongwang/transferlearning/blob/master/data/dataset.md`

`https://github.com/jindongwang/transferlearning/blob/master/doc/benchmark.md`
变成了
`https://github.com/jindongwang/transferlearning/blob/master/data/benchmark.md`

戳[这里](https://github.com/jindongwang/transferlearning-tutorial/blob/master/src/chaps/ch13_appendix.tex#L279)

**Comment by jindongwang** [comment]
谢谢，请提一个pull request
