### ISSUE TITLE
参考文献 bib warning

### ISSUE THREAD

**Issue by tommyjiang** [jindongwang/transferlearning-tutorial#2]
我这边编译的时候，发现 .bib 文件有6处重复的 ref，另外有以下 warning，可以看下如何处理 @jindongwang 

Warning--to sort, need author or key in xinhua
Warning--can't use both volume and number fields in gu2011joint
Warning--can't use both volume and number fields in hu2011transfer
Warning--empty journal in jaini2016online
Warning--empty year in patilknowledge
Warning--empty journal in patilknowledge
Warning--can't use both volume and number fields in sun2016return

**Comment by jindongwang** [comment]
@tommyjiang 我这里没给出提示，你可以先处理一下，commit

**Comment by tommyjiang** [comment]
好的，我处理下提 pull request
