### ISSUE TITLE
missing figure in src/figures

### ISSUE THREAD

**Issue by fengwang** [jindongwang/transferlearning-tutorial#21]
when compiling with xelatex, following error generated:

```
LaTeX Warning: File `./figures/fig-meda-main.pdf' not found on input line 382
```

**Comment by jindongwang** [comment]
Hi, it is rather complex to configure a Chinese latex environment. Therefore, please refer to the overleaf address in the Readme.md file for compiling.

**Comment by jindongwang** [comment]
@fengwang Thanks for your support in this project! I've re-written all things to publish a new book. Please see this article: https://zhuanlan.zhihu.com/p/374927278
