### ISSUE TITLE
您好，手册网站打不开了

### ISSUE THREAD

**Issue by shexuan** [jindongwang/transferlearning-tutorial#23]
您好，手册网站打不开了

**Comment by jindongwang** [comment]
https://tutorial.transferlearning.xyz/
我这里能打开呀

**Comment by shexuan** [comment]
> https://tutorial.transferlearning.xyz/
> 我这里能打开呀

说错了  是这个http://t.cn/RmasEFe 打不开了。。

**Comment by jindongwang** [comment]
感谢指出问题！应该是那个短链接服务失效了，真实的网页地址是：
http://htmlpreview.github.io/?https://github.com/jindongwang/transferlearning-tutorial/blob/master/web/transfer_tutorial.html
我也在readme里更新它，非常感谢！

**Comment by shexuan** [comment]
> 感谢指出问题！应该是那个短链接服务失效了，真实的网页地址是：
> http://htmlpreview.github.io/?https://github.com/jindongwang/transferlearning-tutorial/blob/master/web/transfer_tutorial.html
> 我也在readme里更新它，非常感谢！

没事   感谢大佬的知识分享才是
