### ISSUE TITLE
希望作者可以给个我们怎么把它引用的方法，这样我们可以在论文中引用这个手册，让更多的人知道

### ISSUE THREAD

**Issue by ddholiday** [jindongwang/transferlearning-tutorial#9]
如题，嘿嘿嘿

**Comment by jindongwang** [comment]
好主意，我后期加上。现在引用这个链接也是可以的

2018年4月15日 +0800 11:02 ddholiday <notifications@github.com>，写道：

如题，嘿嘿嘿

**Comment by ufjfeng** [comment]
README 里添加了 bibtex 字段，应该可以 close 了吧
